
package model.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7
 * Tue Oct 29 18:45:33 CET 2013
 * Generated source version: 2.7.7
 */

@XmlRootElement(name = "opResponse", namespace = "http://model/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "opResponse", namespace = "http://model/")

public class OpResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

