<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ServiceImplService" targetNamespace="http://model/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://model/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://model/" schemaLocation="serviceimpl_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="op">
    <wsdl:part name="parameters" element="tns:op">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="opResponse">
    <wsdl:part name="parameters" element="tns:opResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ServiceImpl">
    <wsdl:operation name="op">
      <wsdl:input name="op" message="tns:op">
    </wsdl:input>
      <wsdl:output name="opResponse" message="tns:opResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ServiceImplServiceSoapBinding" type="tns:ServiceImpl">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="op">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="op">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="opResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ServiceImplService">
    <wsdl:port name="ServiceImplPort" binding="tns:ServiceImplServiceSoapBinding">
      <soap:address location="http://localhost:8080/SOAPValueSubstitution/services/ServiceImplPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
