//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.27 at 03:57:10 PM CET 
//


package example.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for student complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="student">
 *   &lt;complexContent>
 *     &lt;extension base="{}person">
 *       &lt;sequence>
 *         &lt;element name="specialField" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "student", propOrder = {
//    "specialField"
//})
@XmlRootElement(name="studentimpl")
public class StudentImpl extends PersonImpl
{

    protected String specialField;

    /**
     * Gets the value of the specialField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialField() {
        return specialField;
    }

    /**
     * Sets the value of the specialField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialField(String value) {
        this.specialField = value;
    }

}
