package model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-29T18:46:16.247+01:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://model/", name = "ServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceImpl {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "op", targetNamespace = "http://model/", className = "model.Op")
    @WebMethod
    @ResponseWrapper(localName = "opResponse", targetNamespace = "http://model/", className = "model.OpResponse")
    public java.lang.String op(
        @WebParam(name = "arg0", targetNamespace = "")
        model.Personne arg0
    );
}
