* Interface Substitution example with SOAP

Thursday October 31st, 2013

Please refer to the article "The Substitution Principle in an Object-Oriented Framework for Web Services: From Failure to Success", 3.1, pp 4-5.

** Added project SOAPInterfaceSubstitution and SOAPInterfaceSubstitutionClient

Initially a client is generated programmatically with SOAP under Eclipse from the server's side code. Then a webservice is changed in the server implementation (for instance op(Eleve e) ): the argument's type is replaced with a supertype (Personne). The test client (SOAPInterfaceSubstitutionClient\src\model\ServiceImpl_ServiceImplPort_Client.java) calls the operation (op in SOAPInterfaceSubstitutionClient\src\model\ServiceImpl.java)with a refined type (Eleve) of the expected argument (Personne p). Note that Eleve maps additional fields (String promo) than Personn in its binding schema. As expected, an error is thrown: 
- Exception in thread "main" javax.xml.ws.soap.SOAPFaultException: Unmarshalling Error: unexpected element (URI : "", local : "promo"). Expected elements are <{}prenom>,<{}nom>
