
package model.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7
 * Tue Oct 29 18:45:33 CET 2013
 * Generated source version: 2.7.7
 */

@XmlRootElement(name = "op", namespace = "http://model/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "op", namespace = "http://model/")

public class Op {

    @XmlElement(name = "arg0")
    private model.Personne arg0;

    public model.Personne getArg0() {
        return this.arg0;
    }

    public void setArg0(model.Personne newArg0)  {
        this.arg0 = newArg0;
    }

}

